HomeTask/HomeTask/Controllers/InstituteManager/GroupManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HomeTask.Core.Mappers;
using HomeTask.Core.ViewModels;
using HomeTask.Managers.Contracts;
using HomeTask.Models.Roles;

namespace HomeTask.Controllers.InstituteManager
{
    [Authorize(Roles = RolesNames.InstituteAdministrator)]
    public class GroupManagerController : BaseController
    {
        private readonly IGroupManager _groupManager;
        private readonly IInstitutionManager _institutionManager;

        private object GetInstitutionID
        {
            get
            {
                return this._institutionManager.GetByUserID(this.CurrentUserID).Id;
            }
        }

        public GroupManagerController(IGroupManager groupManager, IInstitutionManager institutionManager)
        {
            this._groupManager = groupManager;
            this._institutionManager = institutionManager;
        }

        [HttpGet]
        public ActionResult Index(GroupListViewModel viewModel)
        {

            viewModel.GroupViewModels = this._groupManager
                                            .GetAll(this.GetInstitutionID)
                                            .Select(GroupMapper.ToViewModelExpression)
                                            .ToList();

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult AddGroup()
        {
            return this.PartialView("Partial/AddGroup");
        }

        [HttpPost]
        public ActionResult AddGroup(GroupViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var model = viewModel.ToModel();
                this._groupManager.Add(model, this.GetInstitutionID);

                return this.Json(new { success = true });
            }
            return this.Json(new {success = false});
        }

    }
}

HomeTask/HomeTask/Controllers/InstituteManager/StudentManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HomeTask.Core.Helpers;
using HomeTask.Core.Mappers;
using HomeTask.Core.ViewModels;
using HomeTask.Managers.Contracts;
using HomeTask.Models.Roles;

namespace HomeTask.Controllers.InstituteManager
{
    [Authorize(Roles = RolesNames.InstituteAdministrator)]
    public class StudentManagerController : BaseController
    {
        private readonly IStudentManager _studentManager;
        private readonly IInstitutionManager _institutionManager;

        private object GetInstitutionID
        {
            get
            {
                return this._institutionManager.GetByUserID(this.CurrentUserID).Id;
            }
        }

        public StudentManagerController(IStudentManager studentManager, IInstitutionManager institutionManager)
        {
            this._studentManager = studentManager;
            this._institutionManager = institutionManager;
        }

        [ChildActionOnly]
        public ActionResult GetStudentsOfGroup(object groupID)
        {
            var students =
                this._studentManager.GetByGroudID(groupID).Select(x => string.Format("{0} {1}", x.Surname, x.Name));

            return PartialView("Partial/GetStudentsOfGroup",students);
        }

        [HttpGet]
        public ActionResult Index(StudentListViewModel viewModel)
        {
            viewModel.StudentList =
                this._studentManager
                    .GetByInstitute(this.HttpContext.Cache.GetInstitutionID())
                    .Select(StudentMapper.ToViewModelExpression.Compile())
                    .ToList();

            return View(viewModel);
        }

    }
}

HomeTask/HomeTask/Controllers/InstituteManager/SubjectManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HomeTask.Core.Mappers;
using HomeTask.Core.ViewModels;
using HomeTask.Managers.Contracts;
using HomeTask.Models.Roles;

namespace HomeTask.Controllers.InstituteManager
{
    [Authorize(Roles = RolesNames.InstituteAdministrator)]
    public class SubjectManagerController : BaseController
    {
        private readonly ISubjectManager _subjectManager;
        private readonly IInstitutionManager _institutionManager;

        private object GetInstitutionID
        {
            get
            {
                return this._institutionManager.GetByUserID(this.CurrentUserID).Id;
            }
        }

        public SubjectManagerController(ISubjectManager subjectManager, IInstitutionManager institutionManager):base()
        {
            this._subjectManager = subjectManager;
            this._institutionManager = institutionManager;
        }

        [HttpGet]
        public ActionResult GetSubjectForGroup(ulong groupID)
        {
            if (Request.IsAjaxRequest())
            {
                var viewModel = new SubjectListViewModel();
                viewModel.SubjectViewModels =
                    this._subjectManager.GetByGroup(groupID).Select(SubjectMapper.ToViewModelExpression).ToList();

                return PartialView("Partial/GetSubjectOfGroup", viewModel);
            }
            return RedirectToAction("Index", "AdminGroup");
        }

        [HttpGet]
        public ActionResult SubjectEditPage(ulong groupID)
        {
            if (Request.IsAjaxRequest())
            {
                var viewModel = new SubjectEditPageViewModel();
                viewModel.InstituteSubjectsList = this._subjectManager
                                                      .GetByGroup(groupID)
                                                      .Select(x => new SelectListItem()
                                                          {
                                                              Value = x.Id.ToString(),
                                                              Text = x.Name
                                                          });

                viewModel.SubjectViewModels =
                    this._subjectManager.GetByGroup(groupID)
                        .Select(SubjectMapper.ToViewModelExpression.Compile())
                        .ToList();

                return this.PartialView("Partial/EditSubjectOfGroup", viewModel);
            }

            return this.RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult AddSubjectForGroup(SubjectEditPageViewModel viewModel, ulong groupID)
        {
            var subjects = viewModel.SubjectViewModels.Select(SubjectMapper.ToModelExpression.Compile());
            this._subjectManager.AddSubjectForGroup(subjects, groupID);

            return this.Json(new {success = true});
        }



    }
}

HomeTask/HomeTask/Views/GroupManager/Index.cshtml
@using System.Web.Mvc.Html
@using System.Web.Routing
@model HomeTask.Core.ViewModels.GroupListViewModel
@{
    ViewBag.Title = "Группы";
}

@{
    <script type="text/javascript">
        $(document).ready(function () {
            //Show/hide additional of group
            $('.more-toggle').click(function (e) {
                e.preventDefault();

                var groupId = $(this).val('group-id');
                var isVisible = $('tr.group-more[group-id=' + groupId + ']').hasClass('hide');
                if (isVisible) {
                    $('tr.group-more[group-id=' + groupId + ']').removeClass('hide');
                } else {
                    $('tr.group-more[group-id=' + groupId + ']').addClass('hide');
                }
            }
            );
        }
        );
    </script>
}
<legend>Группы</legend>
<a href="@Url.Action("AddGroup","GroupManager")" class="btn modal-window-renderer">Добавить группу</a>
<table class="table">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Название
            </th>
            <th>
                Специальность
            </th>
            <th>
                Количество учеников
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int index = 0;
        }
        @foreach (var group in Model.ElementsForPage)
        {

            <tr>
                <td>
                    @{ ++index;}
                </td>
                <td>@group.Name
                </td>
                <td>@group.Specialty
                </td>
                <td>@group.QuantityOfPupils
                </td>
                <td>
                    <a class="more-toggle" href="#" group-id="@group.ID">Дополнительные сведенья</a>
                </td>
            </tr>
            <tr class="group-more hide" group-id="@group.ID">
                <div class="row-fluid">
                    <div class="span6">
                        <legend>Ученики</legend>
                        @{
                            Html.RenderAction("GetStudentsOfGroup","StudentManager", new { groupID = group.ID} );
                        }
                    </div>
                    <div class="span6">
                        <legend>Предметы</legend>
                        @{
                            Html.RenderAction("GetSubjectForGroup", "SubjectManager", new { groupID = group.ID });
                        }
                        <a href="@Url.Action("SubjectEditPage", "SubjectManager", new { groupID = group.ID })" class="modal-window-renderer">Редактировать предметы</a>
                    </div>
                </div>
            </tr>
        }
    </tbody>
</table>
<div class="pagination">
    <ul>
        @if(Model.CurrentPageIndex > 1)
        {
            <li><a href="@Url.Action("Index", "GroupManager", new { CurrentPageIndex = Model.CurrentPageIndex-1 })">Prev</a></li>
        }
        @for (int i = 1; i <= Model.PageCount; i++)
        {
            <li><a href="@Url.Action("Index", "GroupManager", new { CurrentPageIndex = i })">@i</a></li>
        }
        @if (Model.CurrentPageIndex < Model.PageCount)
        {
            <li><a href="@Url.Action("Index", "GroupManager", new { CurrentPageIndex = Model.CurrentPageIndex+1 })">Next</a></li>
        }
    </ul>
</div>