HomeTask/HomeTask/Controllers/MainMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using HomeTask.Managers.Contracts;
using HomeTask.Models.MainMenu;
using HomeTask.Models.Roles;

namespace HomeTask.Controllers
{
    public class MainMenuController : BaseController
    {
        private readonly ISubjectManager _subjectManager;
        private readonly IStudentManager _studentManager;

        public MainMenuController(ISubjectManager subjectManager, IStudentManager studentManager)
        {
            this._subjectManager = subjectManager;
            this._studentManager = studentManager;
        }

        [ChildActionOnly]
        public ActionResult GetMenu()
        {
            List<MenuItem> menu = new List<MenuItem>();

            //Menu for students
            if (Roles.IsUserInRole(RolesNames.Student))
            {
                menu = new List<MenuItem>()
                    {
                        new MenuItem() {Action = "Index", Controller = "Home", Text = "Главная"},
                        new MenuItem()
                            {
                                Text = "Предметы",
                                SubMenuItems = _subjectManager
                                .GetByGroup(_studentManager.GetByUserID(this.CurrentUserID).GroupID)
                                .ToList()
                                .Select(x => new MenuItem(){ Action = "Index/" + x.Id, Controller = "Task", Text = x.Name})
                                .ToList()
                            }
                    };
            } 
            

            //Menu for teachers
            if (Roles.IsUserInRole(RolesNames.Teacher))
            {
                menu = new List<MenuItem>()
                    {
                        new MenuItem() {Action = "Index", Controller = "Home", Text = "Главная"},
                        new MenuItem() {Action = "Index", Controller = "Group", Text = "Группы"},
                        new MenuItem() {Action = "Index", Controller = "Subjects", Text = "Предметы"}
                    };
            }


            //Menu for institute administrator
            if (Roles.IsUserInRole(RolesNames.InstituteAdministrator))
            {
                menu = new List<MenuItem>()
                    {
                        new MenuItem() {Action = "Index", Controller = "Home", Text = "Главная"},
                        new MenuItem() {Action = "Index", Controller = "AdminGroup", Text = "Группы"},
                        new MenuItem() {Action = "Index", Controller = "AdminTeacher", Text = "Преподаватели"},
                        new MenuItem() {Action = "Index", Controller = "AdminSubject", Text = "Предметы"},
                        new MenuItem() {Action = "Index", Controller = "AdminStudent", Text = "Студенты"}
                    };
            }


            //Menu for super admin
            if (Roles.IsUserInRole(RolesNames.SuperAdmin))
            {
                menu = new List<MenuItem>()
                    {
                        new MenuItem() {Action = "Institutes", Controller = "AdminInsitutes", Text = "Учебные заведения"},
                    };

            }

            var controller = this.ControllerContext.ParentActionViewContext.RouteData.Values["controller"].ToString();

            foreach (var item in menu)
            {
                item.IsSelected = item.Controller == controller;
            }

            return this.PartialView("Partial/MainMenu", menu);
        }
    }
}

HomeTask/HomeTask/Views/Shared/Layout/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="@Url.Content("~/Content/css/bootstrap.css")" />
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js"></script>
        <script type="text/javascript" src="@Url.Content("~/Content/Scripts/jquery.validate.min.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Content/Scripts/jquery.validate.unobtrusive.min.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Content/Scripts/jquery.unobtrusive-ajax.min.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Content/Scripts/bootstrap.min.js")"></script>
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span4">
                   @RenderSection("Login")
                </div>
                <div class="span8">
                    @RenderBody()
                </div>
            </div>
        </div>
    </body>
</html>

HomeTask/HomeTask/Views/Shared/Layout/_Layout.cshtml
@using System.Web.Mvc.Html
@using System.Web.UI.WebControls
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>@(ViewBag.Title ?? "")</title>
    <link rel="stylesheet" href="@Url.Content("~/Content/css/bootstrap.css")" />
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/Scripts/jquery.validate.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/Scripts/jquery.unobtrusive-ajax.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/Scripts/bootstrap.min.js")"></script>
    <script type="text/javascript">
        $(ducument).ready(function () {
            $('.modal-window-renderer').click(function (e) {
                e.preventDefault();
                var url = $(this).attr('href');
                $.get(url, function (data) {
                    $('#modalWindow').empty();
                    $('#modalWindow').html(data);
                    $('#modalWindow').modal('show');
                });
            });

            $('.close-modal-window').click(function (e) {
                e.preventDefault();
                $('#modalWindow').modal('hide');
            });


            $('.submit-form').live("onsubmit", function (e) {
                e.preventDefault();
                var url = $(this).attr('action');
                $.post(url, $(this).serialize(),
                    function (data) {
                        if (data.success) {
                            $('#modalWindow').modal('hide');
                        } else {
                            alert("Ошибка! Что-то пошло не правильно...");
                        }
                    });
            });
        })
    </script>
    @this.RenderSection("header", false)
</head>
<body>
    @{
        Html.RenderAction("GetMenu", "MainMenu"); 
    }
    <div class="container-fluid">
        <div class="row-fluid">
            @this.RenderBody()
        </div>
    </div>
    <div class="modal hide fade" id="modalWindow">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                &times;</button>
            <h3>
                Modal header</h3>
        </div>
        <div class="modal-body">
            <p>
                One fine body…</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn">Close</a> <a href="#" class="btn btn-primary"></a>
        </div>
    </div>
</body>
</html>

HomeTask/HomeTask/Views/Shared/Layout/_LayoutLogOn.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="@Url.Content("~/Content/css/bootstrap.css")" />
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/Scripts/jquery.validate.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/Scripts/bootstrap.min.js")"></script>
    <title>@ViewBag.Title</title>
    @RenderSection("header", false)
</head>
    <body>
        <div class="container">
            <div class="row-fluid">
            <div class="span4">@RenderBody()</div>
            <div class="span8"></div>
            </div>

        </div>
    </body>
</html>

HomeTask/HomeTask/Views/Shared/Layout/_TaskLayout.cshtml
@{
    ViewBag.Title = "_TaskLayout";
    Layout = "~/Views/Shared/Layout/_Layout.cshtml";
}
<div class="row">
    <div class="span3">@RenderSection("TaskMenu")</div>
    <div class="span6">@RenderSection("TaskBody")</div>
</div>